/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////

public typealias AutoActivityDetect = UInt32

public struct AutoActivityDetectValues: Sendable {
    public static let none: AutoActivityDetect = 0x00000000
    public static let running: AutoActivityDetect = 0x00000001
    public static let cycling: AutoActivityDetect = 0x00000002
    public static let swimming: AutoActivityDetect = 0x00000004
    public static let walking: AutoActivityDetect = 0x00000008
    public static let elliptical: AutoActivityDetect = 0x00000020
    public static let sedentary: AutoActivityDetect = 0x00000400
    public static let invalid: AutoActivityDetect = 0xFFFFFFFF
}
